### ISSUE TITLE
Panic: Resource 'BitmexConnectErrorSubscribeMarketData' not defined in 'CustomAdapter.Resource'

### ISSUE THREAD

**Issue by sblanchard** [BitMEX/ninjatrader-bitmex#15]
I get this error when selecting XBTUSD

nt8 - 8.0.13.1 64-bit 

2018-04-30 12:25:00:694 (My BitMEX) BitmexConnect.SubscribeMarketData Exception=System.ArgumentException: The conversion could not be completed because the supplied DateTime did not have the Kind property set correctly.  For example, when the Kind property is DateTimeKind.Local, the source time zone must be TimeZoneInfo.Local.
Parameter name: sourceTimeZone
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
   at NinjaTrader.Data.MarketReplay.OnMarketData(MarketDataType marketDataType, Double price, Int64 volume, DateTime timeLocal)
   at NinjaTrader.Cbi.Instrument.MarketDataHandling(MarketDataEventArgs e)
   at NinjaTrader.Cbi.Instrument.MarketDataCallback(MarketDataType marketDataType, Double price, Int64 volume, DateTime time, Int64 tickId)
   at NinjaTrader.NinjaScript.Adapters.NinjaTraderAdapter.<>c__DisplayClass26_0.<SubscribeMarketData>b__0(Int32 dataType, Double price, Int64 size, DateTime timestamp)
   at BitmexConnect.BitmexConnector.SubscribeMarketData(String symbol, Action`4 marketDataCallback)
   at NinjaTrader.NinjaScript.Adapters.NinjaTraderAdapter.SubscribeMarketData(Instrument instrument, Action`5 callback)
2018-04-30 12:25:00:695 ERROR: Panic: Resource 'BitmexConnectErrorSubscribeMarketData' not defined in 'CustomAdapter.Resource'
2018-04-30 12:25:00:704 Cbi.Instrument.RequestBars (to Provider): instrument='XBTUSD' from='30/04/2018 00:00:00' to='30/04/2018 00:00:00' period='1 Minute'
2018-04-30 12:25:39:740 ---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
no instruments selected, probably a futures with invalid rollover/expiries
---- Assert Long Message ----

   at NinjaTrader.Gui.Tools.InstrumentSelectorPopup.OnSearchClicked(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at NinjaTrader.Gui.Tools.NTWindow.ShowDialog()
   at NinjaTrader.Gui.ControlCenter.<OnInstrumentLists>b__99_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at NinjaTrader.Core.Globals.<>c__DisplayClass167_1.<get_RandomDispatcher>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ryanfox** [comment]
What action specifically triggers the error? What window, how you got there, any actions you did before, any more info is helpful.

**Comment by sblanchard** [comment]
1) Import the plugin
2) Create a instrument list for the instruments
3) Add all the BitMex instruments to the list
4) Go to Chart and select BitMex -> XBTUSD

I've done database resets etc and the problem persists.

**Comment by sblanchard** [comment]
Don't suppose you will release the source code so that I can debug this? (This is github after all)

**Comment by ryanfox** [comment]
I'm having trouble reproducing the bug. When you say add all the BitMEX instruments to the list - are you doing this one by one? For what purpose?

If you skip the instrument list and just create an XBTUSD chart, do you get the error message?

**Comment by sblanchard** [comment]
Adding this line above the callback in SubscribeMarketData fixes it btw

var dt = DateTime.SpecifyKind(timestamp, DateTimeKind.Unspecified);
callback((Data.MarketDataType)dataType, price, size, dt, 0L);

**Comment by ryanfox** [comment]
This issue should be resolved with [release v1.0.10.](https://github.com/BitMEX/ninjatrader-bitmex/releases/tag/v1.0.10)
