### ISSUE TITLE
no historical data

### ISSUE THREAD

**Issue by tickcharter** [BitMEX/ninjatrader-bitmex#16]
hello, im following the guide charting xbtusd in nt8
my issue is, in my new chart, there is no historical data. It's connect to bitmex but the data always start at new datafeed, there is no past data before that. And when im close it, it always begin again from new datafeed.
Example is, xbtusd now at 9040, there is no data before 9040.
Hope i can get answer in here, thank you
![capture](https://user-images.githubusercontent.com/38916687/39528785-3ed3c942-4e4f-11e8-8f20-58fb56b12387.PNG)

**Comment by sblanchard** [comment]
Tick replay enabled?

**Comment by tickcharter** [comment]
I'm already trying download historical data, but still no result.

@sblanchard where is this tick replay enabled? sorry for asking, because im still new using nt8

@ryanfox is the option is when we gonna make new chart or in download historical data menu?

**Comment by tickcharter** [comment]
im trying tick replay enabled, no results, specify data range also no result.
in options - market data - general, historical and real data, i use bitmex for stock, forex, and futures
and in historical, i enable show tick replay.
im restarting nt8, but in chart, im only got loading...

**Comment by sblanchard** [comment]
have you tried turning tick replay off and only loading some 5 minute bars for 1 day?

**Comment by sblanchard** [comment]
this plugin seems a bit finicky on newer builds of ninja for some reason. I've had to uninstall and delete my whole folder because I still got some error on it insisting to start downloading Tick data for an instrument despite not having any chart or anything open yet. I've got an older build on another pc where it's working better.

**Comment by tickcharter** [comment]
@sblanchard yeah im trying that, still only loading..., still no result :/

**Comment by sblanchard** [comment]
Check your trace files for any errors and paste them here

C:\Users\xxx\Documents\NinjaTrader 8\trace

**Comment by sblanchard** [comment]
Same error I had... I gave them the solution

2018-05-06 11:18:46:187 Cbi.Instrument.RequestBars (to Provider): instrument='XBTUSD' from='30/04/2018 00.00.00' to='06/05/2018 00.00.00' period='1 Minute'
2018-05-06 11:18:47:563 error retrieving data: The remote server returned an error: (400) Bad Request.
2018-05-06 11:18:47:866 subscribing to quotes for XBTUSD
2018-05-06 11:18:47:866 first quote subscription, connecting to bitmex websocket for quotes
2018-05-06 11:18:47:901 first trade subscription, connecting to bitmex websocket for instrument XBTUSD
2018-05-06 11:18:47:917 Cbi.Instrument.RequestBars (to Provider): instrument='XBTUSD' from='06/05/2018 00.00.00' to='06/05/2018 00.00.00' period='1 Minute'
2018-05-06 11:18:48:067 (My BitMEX) BitmexConnect.SubscribeMarketData Exception=System.ArgumentException: The conversion could not be completed because the supplied DateTime did not have the Kind property set correctly.  For example, when the Kind property is DateTimeKind.Local, the source time zone must be TimeZoneInfo.Local.
Parameter name: sourceTimeZone
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
   at NinjaTrader.Data.MarketReplay.OnMarketData(MarketDataType marketDataType, Double price, Int64 volume, DateTime timeLocal)
   at NinjaTrader.Cbi.Instrument.MarketDataHandling(MarketDataEventArgs e)
   at NinjaTrader.Cbi.Instrument.MarketDataCallback(MarketDataType marketDataType, Double price, Int64 volume, DateTime time, Int64 tickId)
   at NinjaTrader.NinjaScript.Adapters.NinjaTraderAdapter.<>c__DisplayClass26_0.<SubscribeMarketData>b__0(Int32 dataType, Double price, Int64 size, DateTime timestamp)
   at BitmexConnect.BitmexConnector.SubscribeMarketData(String symbol, Action`4 marketDataCallback)
   at NinjaTrader.NinjaScript.Adapters.NinjaTraderAdapter.SubscribeMarketData(Instrument instrument, Action`5 callback)
2018-05-06 11:18:48:074 ERROR: Panic: Resource 'BitmexConnectErrorSubscribeMarketData' not defined in 'CustomAdapter.Resource'
2018-05-06 11:18:48:339 error retrieving data: The remote server returned an error: (400) Bad Request.
2018-05-06 11:19:13:618 Cbi.Instrument.RequestBars (to Provider): instrument='XBTUSD' from='04/05/2018 00.00.00' to='06/05/2018 00.00.00' period='1 Minute'
2018-05-06 11:19:14:439 error retrieving data: The remote server returned an error: (400) Bad Request.
2018-05-06 11:19:29:090 Cbi.Instrument.RequestBars (to Provider): instrument='XBTUSD' from='04/05/2018 00.00.00' to='06/05/2018 00.00.00' period='1 Minute'
2018-05-06 11:19:29:460 error retrieving data: The remote server returned an error: (400) Bad Request.
2018-05-06 11:20:51:592 Cbi.Instrument.RequestBars (to Provider): instrument='XBTUSD' from='29/04/2018 00.00.00' to='06/05/2018 00.00.00' period='1 Minute'
2018-05-06 11:20:52:075 error retrieving data: The remote server returned an error: (400) Bad Request.

**Comment by tickcharter** [comment]
@sblanchard how to apply your solution?

**Comment by sblanchard** [comment]
I can't attach it unfort...need programming knowledge and they should either open source the code or fix it.

**Comment by tickcharter** [comment]
so..no solutions for me now i guess hehe..thank you for always answering and trying to help @sblanchard

**Comment by ryanfox** [comment]
@sblanchard You can specify a date range in the chart creation widget. The section labeled "Time Frame".

**Comment by sblanchard** [comment]
Yes the default is 5 days, he's actually getting an error if you check the last trace file.

**Comment by Cap135** [comment]
Doesn't work to on ninja8. There is connect but no data.

**Comment by yanyr** [comment]
Hi,

I can load some historical data to the chart but I'm not able to load historical data for playback. I would like to use playback because I want to see historical Level II depth chart data also. Is it possible to solve it somehow?

Thanks

**Comment by tayron123** [comment]
i did andestend:))))))))
